# Generated by Django 3.1.7 on 2021-02-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionlist', '0003_auto_20210221_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject_id',
        ),
    ]
