# Generated by Django 3.1.7 on 2021-02-21 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionlist', '0004_remove_question_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionlist.subject'),
            preserve_default=False,
        ),
    ]
